#set -g default-terminal "tmux-256color"
set -g default-terminal "xterm-256color"
#set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides ",xterm-256color:Tc"
# action key
set-option -g repeat-time 500
set-option -g focus-events on

#### Key bindings
set-window-option -g mode-keys vi

#bind t send-key C-d
# Reload settings
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"
# Kill all other pane
bind -r e kill-pane -a

#### basic settings
set -g window-style fg=colour10,bg=default
set -g window-active-style fg=colour12,bg=default
set-option -g history-limit 65535

set -sg escape-time 10

# allow the title bar to adapt to whatever host you connect to
set -g set-titles on
set -g set-titles-string "#T"

source ~/.config/tmux/statusline.conf

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-pain-control'
run '~/.config/tmux/plugins/tpm/tpm'

